site_name: OpenL Tablets
site_url: https://openl.readthedocs.io/en/latest/
edit_uri: edit/main/docs/
nav:
    - Installation Guide: documentation/guides/installation_guide.md
    - Demo Package Guide: documentation/guides/demo_package_guide.md
    - For Business Users: 
      - Reference Guide: documentation/guides/reference_guide.md
      - WebStudio User Guide: documentation/guides/webstudio_user_guide.md
    - For Developers:
      - Rule Services Usage and Customization Guide: documentation/guides/rule_services_usage_and_customization_guide.md
      - Developer Guide: documentation/guides/developer_guide.md
      - Activiti Integration Guide: documentation/guides/activiti_integration_guide.md
    - About OpenL: about.md
  
theme: 
    name: material
    navigation_depth: 8
    theme_dir: site/css/theme_override
    custom_dir: site/css/theme_override
    logo: assets/logo.png
    features:
    - content.action.edit
    - content.action.view

repo_url: https://github.com/EISTW/OpenLdocs/

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.superfences
  - toc:
      permalink: True
  
extra_css:
    - css/extra.css
